// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var initialModel = {
  value: 0
};

function update(model, action) {
  if (action) {
    return {
            value: model.value - 1 | 0
          };
  } else {
    return {
            value: model.value + 1 | 0
          };
  }
}

function view(model, dispatch, param, props) {
  var App = function (Props) {
    return React.createElement("button", {
                onClick: (function (param) {
                    return Curry._1(dispatch, /* Add */0);
                  })
              }, "Add");
  };
  var remove = function (param) {
    return React.createElement("button", {
                onClick: (function (param) {
                    return Curry._1(dispatch, /* Remove */1);
                  })
              }, "Remove");
  };
  return React.createElement("div", undefined, React.createElement("h1", undefined, props.title), React.createElement("h2", undefined, "Counter: " + String(model.value)), React.createElement(App, {}), remove(undefined));
}

function initEffects(model, dispatch) {
  
}

function useSubscribe(model, dispatch) {
  
}

function componentInitialization(model) {
  return model;
}

function make(props) {
  var match = React.useReducer(update, initialModel, componentInitialization);
  var dispatch = match[1];
  var model = match[0];
  var param;
  return view(model, dispatch, param, props);
}

export {
  initialModel ,
  update ,
  view ,
  initEffects ,
  useSubscribe ,
  componentInitialization ,
  make ,
  
}
/* react Not a pure module */
