// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RMV from "./RMV.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function update(model, action) {
  if (action) {
    return {
            value: model.value - 1 | 0
          };
  } else {
    return {
            value: model.value + 1 | 0
          };
  }
}

var initialModel = {
  value: 0
};

function view(model, dispatch, props) {
  var FunctorTest$Definition = function (Props) {
    return React.createElement("button", {
                onClick: (function (param) {
                    return Curry._1(dispatch, /* Add */0);
                  })
              }, "Add");
  };
  var FunctorTest$Definition$1 = function (Props) {
    return React.createElement("button", {
                onClick: (function (param) {
                    return Curry._1(dispatch, /* Remove */1);
                  })
              }, "Remove");
  };
  return React.createElement("div", undefined, React.createElement("h1", undefined, props.title), React.createElement("h2", undefined, "Counter: " + String(model.value)), React.createElement(FunctorTest$Definition, {}), React.createElement(FunctorTest$Definition$1, {}));
}

var Definition = {
  update: update,
  initialModel: initialModel,
  view: view
};

var include = RMV.ModelViewProps({
      initialModel: initialModel,
      update: update,
      view: view
    });

var useMake = include.useMake;

var make = include.make;

export {
  Definition ,
  useMake ,
  make ,
  
}
/* include Not a pure module */
