// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FetchComp from "./FetchComp.bs.js";
import * as FunctorTest from "./FunctorTest.bs.js";

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("section", undefined, React.createElement(FunctorTest.make, {
                      title: "Test prop pass"
                    })), React.createElement(FetchComp.make, {
                  url: "https://61085becd73c6400170d391e.mockapi.io/names"
                }));
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
