// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FunctorTest from "./FunctorTest.bs.js";

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("section", undefined, React.createElement(FunctorTest.make, {
                      title: "Test prop pass"
                    })));
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
