// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(props) {
  return React.createElement("h1", undefined, props.title);
}

export {
  make ,
  
}
/* react Not a pure module */
