// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(props) {
  var match = React.useState(function () {
        return props.title;
      });
  return React.createElement("h1", undefined, match[0]);
}

export {
  make ,
  
}
/* react Not a pure module */
